os: linux
dist: xenial
sudo: required
addons:
  apt:
    update: true
    packages:
    - git
    - pxz
    - wput
before_install: git clone https://github.com/ZeoRexDevs/test_android_norepos.git ${TRAVIS_BUILD_DIR}/tranSkadooSH
script:
  - printf '%s\n' '#!/bin/sh' '' 'echo $$ >> act_sh.pid' 'while true; do' '  echo -en "The Time is --- "' "  date +%r" '  sleep 300' 'done' >${TRAVIS_BUILD_DIR}/tranSkadooSH/act.sh
  - cd ${TRAVIS_BUILD_DIR}/tranSkadooSH
  - chmod +x ./transload.sh ./act.sh
  - echo "Running..."; ./act.sh & ./transload.sh $AndroidName $LINK $BRANCH $GitHubMail $GitHubName $FTPHost $FTPUser $FTPPass
  - kill $(cat act_sh.pid) || echo "Process is not running."
after_success: echo "Congratulations! Job Done!"
deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GitOAUTHToken"
  file_glob: true
  file: ${TRAVIS_BUILD_DIR}/tranSkadooSH/upload/$AndroidName-$BRANCH*
  on:
    tags: false
    repo: ZeoRexDevs/test_android_norepos
    branch: master
branches:
  except:
    - /^(?i:untagged)-.*$/
after_deploy:
  - cd ${TRAVIS_BUILD_DIR}/ && rm -rf tranSkadooSH/
  - echo "Cleanup Done!"
notifications:
  email:
  - rokibhasansagar2014@outlook.com
